<?php

namespace Database\Seeders;

use App\Models\FinanceTransaction;
use App\Models\User;
use Illuminate\Database\Seeder;

class FinanceTransactionSeeder extends Seeder
{
    public function run(): void
    {
        $owner = User::where('role', 'owner')->first();
        $userId = $owner ? $owner->id : null;

        $transactions = [
            // 1. PEMBELIAN BAHAN BAKU KACA KE SUPPLIER (HPP / COGS)
            [
                'transaction_code' => 'PO-BB-202608-001',
                'type' => 'pembelian_bahan',
                'category' => 'Bahan Kaca Lembaran',
                'title' => 'Pembelian 25 Lembar Kaca Cermin 5mm Asahimas (183x244 cm)',
                'amount' => 18750000,
                'supplier_name' => 'PT Asahimas Flat Glass Tbk (Divisi Cermin)',
                'invoice_number' => 'INV-ASA-2026/08/042',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-04',
                'due_date' => null,
                'notes' => 'Restock rutin kaca cermin lembaran standard gudang bahan baku',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'PO-BB-202608-002',
                'type' => 'pembelian_bahan',
                'category' => 'Bahan Kaca Lembaran',
                'title' => 'Pembelian 15 Lembar Kaca Tempered 10mm Clear Mulia (214x305 cm)',
                'amount' => 24300000,
                'supplier_name' => 'PT Mulia Glass Float & Mirror',
                'invoice_number' => 'INV-MLG-88219',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-11',
                'due_date' => null,
                'notes' => 'Bahan tempered untuk proyek partisi kantor Dago & Gedung Wisma',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'PO-BB-202608-003',
                'type' => 'pembelian_bahan',
                'category' => 'Bahan Kaca Lembaran',
                'title' => 'Pembelian 10 Lembar Kaca Tinted Dark Grey 8mm Import',
                'amount' => 14200000,
                'supplier_name' => 'PT Global Tinted Glass Import',
                'invoice_number' => 'INV-GTG-0912',
                'payment_method' => 'Tempo 30 Hari',
                'payment_status' => 'Tempo',
                'transaction_date' => '2026-08-18',
                'due_date' => '2026-09-18',
                'notes' => 'Faktur jatuh tempo 30 hari kalender, DP sudah disetorkan 20%',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'PO-BB-202608-004',
                'type' => 'pembelian_bahan',
                'category' => 'Bahan Kaca Lembaran',
                'title' => 'Pembelian 8 Lembar Kaca Laminated 5+5mm Acoustic Safety',
                'amount' => 16400000,
                'supplier_name' => 'PT Kaca Tempered Nusantara',
                'invoice_number' => 'INV-KTN-7741',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-25',
                'due_date' => null,
                'notes' => 'Kaca laminated kanopi & void skylight pesanan khusus',
                'user_id' => $userId,
            ],

            // 2. PEMBELIAN AKSESORIS KACA KONSUMEN (HPP / COGS)
            [
                'transaction_code' => 'PO-ACC-202608-001',
                'type' => 'pembelian_aksesoris',
                'category' => 'Aksesoris Kaca',
                'title' => 'Restock 20 Set Handle Pintu Kaca Tubular SS-304 & 10 Box Sealant Netral',
                'amount' => 7450000,
                'supplier_name' => 'Distributor Hardware Dekkson Mandiri',
                'invoice_number' => 'DKS-HARD-491',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-06',
                'notes' => 'Aksesoris handle pintu shower & kaca frameless toko',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'PO-ACC-202608-002',
                'type' => 'pembelian_aksesoris',
                'category' => 'Aksesoris Kaca',
                'title' => 'Restock 8 Set Floor Hinge BTS-84 & Patch Fitting Set Top/Bottom',
                'amount' => 9600000,
                'supplier_name' => 'PT Dorma Aksesoris Prima',
                'invoice_number' => 'DRM-INV-3012',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-16',
                'notes' => 'Aksesoris pintu utama kaca gedung & ruko',
                'user_id' => $userId,
            ],

            // 3. PEMBELIAN ALAT & PERLENGKAPAN PABRIK / GUDANG (ALAT PENUNJANG)
            [
                'transaction_code' => 'PO-ALT-202608-001',
                'type' => 'pembelian_alat',
                'category' => 'Alat & Mesin',
                'title' => 'Pengadaan 4 Set Mata Bor Kaca Diamond Coated & 5 Pcs Piringan Polishing',
                'amount' => 3850000,
                'supplier_name' => 'Toko Teknik Industri Jaya Sentosa',
                'invoice_number' => 'TKN-29401',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-08',
                'notes' => 'Kebutuhan Divisi HT (Potong/Bor) dan Divisi GM (Gosok Halus)',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'PO-ALT-202608-002',
                'type' => 'pembelian_alat',
                'category' => 'Alat & Mesin',
                'title' => 'Pembelian 2 Unit Suction Cup Vakum Driver & 6 Pasang Sarung Tangan Kevlar',
                'amount' => 2150000,
                'supplier_name' => 'Safety Glass Equipment Specialist',
                'invoice_number' => 'SFT-GLS-802',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-19',
                'notes' => 'Perlengkapan safety handling driver armada & pekerja potong',
                'user_id' => $userId,
            ],

            // 4. BEBAN OPERASIONAL PABRIK & TOKO (OPEX)
            [
                'transaction_code' => 'EXP-202608-001',
                'type' => 'biaya_operasional',
                'category' => 'Listrik & Energi Pabrik',
                'title' => 'Tagihan Listrik PLN Industri Pabrik Mesin Gosok, Oven & Bevel',
                'amount' => 11840000,
                'supplier_name' => 'PT PLN (Persero) Rayon Industri',
                'invoice_number' => 'PLN-IND-541289',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-10',
                'notes' => 'Beban pemakaian daya 33 kVA pabrik manufaktur kaca',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'EXP-202608-002',
                'type' => 'biaya_operasional',
                'category' => 'BBM & Logistik Armada',
                'title' => 'BBM Solar Truk Engkel Box & Mobil L300 Pengiriman Wilayah Jabar',
                'amount' => 4650000,
                'supplier_name' => 'SPBU Pertamina Pasti Pas',
                'invoice_number' => 'STR-BBM-202608',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-15',
                'notes' => 'Reimburse BBM delivery trip Bandung, Subang, Cimahi, dan Cirebon',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'EXP-202608-003',
                'type' => 'biaya_operasional',
                'category' => 'Gaji & Upah Lembur',
                'title' => 'Gaji Pokok & Uang Lembur Shift Malam Divisi HT, GM, BV, Etsa, & Driver',
                'amount' => 19500000,
                'supplier_name' => 'Internal Karyawan SYP Glass',
                'invoice_number' => 'PAYROLL-2026/08',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-28',
                'notes' => 'Total penggajian 10 staf divisi operasional & supir pengiriman',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'EXP-202608-004',
                'type' => 'biaya_operasional',
                'category' => 'Perawatan Mesin',
                'title' => 'Servis Berkala Mesin Edging Straight & Penggantian Vanbelt Conveyor',
                'amount' => 2800000,
                'supplier_name' => 'Bengkel Teknik Presisi Mesin Kaca',
                'invoice_number' => 'SRV-EDG-492',
                'payment_method' => 'Transfer Bank BCA',
                'payment_status' => 'Lunas',
                'transaction_date' => '2026-08-22',
                'notes' => 'Perawatan preventif mesin agar kualitas gosokan halus tetap maksimal',
                'user_id' => $userId,
            ],
            [
                'transaction_code' => 'EXP-202608-005',
                'type' => 'biaya_operasional',
                'category' => 'Operasional Kantor',
                'title' => 'Internet Fiber Optic Toko, ATK Nota SPK, & Kebutuhan Konsumsi Staff',
                'amount' => 1450000,
                'supplier_name' => 'Kantin & Toko ATK Sejahtera',
                'invoice_number' => 'ATK-OPS-083',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'approval_status' => 'approved',
                'source_role' => 'admin_toko',
                'transaction_date' => '2026-08-24',
                'notes' => 'Kebutuhan administratif toko & operasional kasir harian',
                'user_id' => $userId,
            ],

            // 5. KLAIM OPERASIONAL SUPIR ARMADA PENGIRIMAN (DRIVER FLEET CLAIMS)
            [
                'transaction_code' => 'KLM-DRV-202608-001',
                'type' => 'biaya_operasional',
                'category' => 'BBM Armada',
                'title' => 'Klaim Solar Dexlite Armada Truk Engkel (Pak Budi)',
                'amount' => 280000,
                'supplier_name' => 'SPBU Pertamina 34-40116',
                'invoice_number' => 'NOTA-SPBU-8912',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'approval_status' => 'pending',
                'source_role' => 'driver',
                'vehicle_plate' => 'B 9482 SYP (Truk Engkel)',
                'transaction_date' => '2026-08-28',
                'notes' => 'Pengisian BBM solar rute pengiriman kaca tempered Dago & Gedung Wisma',
                'user_id' => User::where('role', 'driver')->first()?->id ?? $userId,
            ],
            [
                'transaction_code' => 'KLM-DRV-202608-002',
                'type' => 'biaya_operasional',
                'category' => 'BBM Armada',
                'title' => 'Klaim E-Toll & Parkir Proyek Antapani (Pak Asep)',
                'amount' => 145000,
                'supplier_name' => 'Gerbang Tol Buah Batu & Parkir Lapangan',
                'invoice_number' => 'TOLL-STRUK-441',
                'payment_method' => 'Kas Tunai',
                'payment_status' => 'Lunas',
                'approval_status' => 'approved',
                'source_role' => 'driver',
                'vehicle_plate' => 'D 8102 SYP (Pikap L300)',
                'transaction_date' => '2026-08-20',
                'approved_by_user_id' => $userId,
                'approved_at' => '2026-08-20 16:30:00',
                'notes' => 'E-toll Pasteur - Buah Batu PP dan retribusi bongkar kaca di proyek',
                'user_id' => User::where('role', 'driver')->skip(1)->first()?->id ?? $userId,
            ],
        ];

        foreach ($transactions as $trx) {
            FinanceTransaction::updateOrCreate(
                ['transaction_code' => $trx['transaction_code']],
                array_merge(['approval_status' => 'approved'], $trx)
            );
        }
    }
}
